# Generated by Django 5.2.11 on 2026-03-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
