# Generated by Django 4.2.29 on 2026-03-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_searchquery_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='links_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='videos_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
